[2023-12-10 19:40:32,309] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-04-07T00:00:00+00:00 [queued]>
[2023-12-10 19:40:32,527] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-04-07T00:00:00+00:00 [queued]>
[2023-12-10 19:40:32,558] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:40:32,572] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:40:32,578] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:40:32,849] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-04-07 00:00:00+00:00
[2023-12-10 19:40:32,951] {standard_task_runner.py:52} INFO - Started process 2725 to run task
[2023-12-10 19:40:32,983] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-04-07T00:00:00+00:00', '--job-id', '754', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpynwzfdip', '--error-file', '/tmp/tmpwrqaba7o']
[2023-12-10 19:40:33,044] {standard_task_runner.py:80} INFO - Job 754: Subtask segunda_tarea
[2023-12-10 19:40:34,333] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-04-07T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:40:35,992] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-04-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-07T00:00:00+00:00
[2023-12-10 19:40:36,040] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:40:36,063] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:40:36,231] {subprocess.py:85} INFO - Output:
[2023-12-10 19:40:36,252] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:40:36,275] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:40:38,371] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20230407T000000, start_date=20231210T194032, end_date=20231210T194038
[2023-12-10 19:40:39,039] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
